# This workflow will publish a package when a release is created

name: Publish package to NuGet repository
on:
  release:
    types: [created]
jobs:
  publish-nuget:  
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '3.1.x'
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
      - name: Build solution and generate NuGet package
        run: |
          dotnet pack -c Release -o out
          echo ls

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./contentstack-utils-dotnet/out/*.nupkg --api-key $NUGET_AUTH_TOKEN --source https://www.nuget.org/ --skip-duplicate --no-symbols true

  publish-git:  
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
          source-url: https://nuget.pkg.github.com/Contentstack/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build solution and generate NuGet package
        run: |
          dotnet pack -c Release -o out

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./contentstack-utils-dotnet/out/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate --no-symbols true
