name: Source Composition Analysis Scan
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  security-sca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.3
      - name: Restore dependencies
        run: dotnet restore ./Contentstack.Utils.sln
      - name: Run Snyk to check for vulnerabilities
        run: cd Contentstack.Utils && snyk test --fail-on=all
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
